airfare <- read.csv("C:/Users/vigupta/OneDrive/Learning/DataScience/Statistics Texas A&M University/608/SheatherBook/Data/airfares.txt", header = T, sep ="" )
plot(airfare$Distance,airfare$Fare)
fit.1 <- lm(airfare$Fare~airfare$Distance)
plot(fit.1)

hatvalues(fit.1)
str(airfare)
cd=cooks.distance(fit.1)
plot(airfare$Distance,cd)
abline(h=4/17,lty=2)
identify(airfare$Distance,cd)
plot(airfare$Distance, rstandard(fit.1))
abline(h=-2,lty=2)
abline(h=2,lty=2)
identify(airfare$Distance, rstandard(fit.1))


fit.2 <- lm(newairfare$Fare~newairfare$Distance)
plot(fit.2)

fit.2 <- lm(newairfare$Fare~newairfare$Distance)
airfare3 <- data.frame(city=newairfare$City,fare=newairfare$Fare,dist=newairfare$Distance,distSq=newairfare$Distance^2)
fit.3 <- lm(airfare3$fare ~ airfare3$dist + airfare3$distSq)
plot(fit.3)
y<- log(airfare$Fare)
x <- log(airfare$Distance)
fit.4 <- lm(y~x)
plot(fit.4)
qqnorm(airfare$Fare)
shapiro.test(airfare$Fare)
library(car)
bcp(airfare$Distance)
fit.5 <- lm(airfare3$fare ~ -airfare3$distSq)
summary(fit.5)

plot(fit.1)
library("alr3")
invResPlot(fit.1,lambda=c(-1,-1/3,-1/4,-1/5,0,1/5,1/4/1/3,1))
bcPower(airfare$Distance,lambda=c(-1,-1/3,-1/4,-1/5,0,1/5,1/4/1/3,1))
plot(density(y))

cd2=cooks.distance(fit.2)
plot(airfare3$dist,cd2)
identify(airfare3$dist,cd2)
abline(h=4/17,lty=2)
hatvalues(fit.3)
